FROM alpine:3.20
LABEL org.opencontainers.image.title="Custom NFS Server"
LABEL org.opencontainers.image.description="Custom NFS Server to be used for internal services on Kubernetes homelab, Single NODE"
LABEL org.opencontainers.image.source="https://github.com/csbdc/custom-nfs"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.vendor="CSBDC"

RUN apk add --no-cache \
    nfs-utils \
    rpcbind \
    bash \
    util-linux \
    iproute2

# Required NFS state dirs (IMPORTANT on Alpine)
RUN mkdir -p \
    /exports \
    /var/lib/nfs \
    /var/lib/nfs/rpc_pipefs

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 111 2049

CMD ["/entrypoint.sh"]